# Sudoku Solver

In [42]:
import numpy as np
import math

In [43]:
def get_subgrid_indices(r,c):
    sg_row_start = math.floor(r/3) * 3
    sg_row_end = sg_row_start + 3
    sg_col_start = math.floor(c/3) * 3
    sg_col_end = sg_col_start + 3
    return (sg_row_start,sg_row_end,sg_col_start,sg_col_end)

In [44]:
def is_number_possible_in_position(number,r,c,grid):
    not_in_row = not(number in grid[r,:])
    not_in_column = not(number in grid[:,c]) 
    (sg_row_start,sg_row_end,sg_col_start,sg_col_end) = get_subgrid_indices(r,c)
    not_in_subgrid = not(number in grid[sg_row_start:sg_row_end,sg_col_start:sg_col_end])
    return not_in_row and not_in_column and not_in_subgrid 

In [45]:
def solve():
    for r in range(9):
        for c in range(9):
            if(grid[r][c] == 0):
                for number in range(1,10):
                    if(is_number_possible_in_position(number,r,c,grid)):
                        grid[r][c] = number
                        solve()
                        grid[r][c] = 0
                return
    print('Solution')
    print(grid)                     

In [46]:
grid = np.array([
    [0,0,5,2,0,0,0,7,0],
    [0,0,3,0,0,1,0,0,0],
    [0,2,0,0,0,0,0,0,5],
    [6,7,0,0,0,0,4,8,0],
    [0,0,1,9,0,0,0,0,0],
    [0,0,0,7,0,0,3,0,0],
    [0,8,4,0,5,0,6,0,0],
    [1,0,0,0,0,4,0,0,0],
    [0,9,0,0,0,0,0,0,7]
])
print("Input")
print(grid)
solve()

Input
[[0 0 5 2 0 0 0 7 0]
 [0 0 3 0 0 1 0 0 0]
 [0 2 0 0 0 0 0 0 5]
 [6 7 0 0 0 0 4 8 0]
 [0 0 1 9 0 0 0 0 0]
 [0 0 0 7 0 0 3 0 0]
 [0 8 4 0 5 0 6 0 0]
 [1 0 0 0 0 4 0 0 0]
 [0 9 0 0 0 0 0 0 7]]
Solution
[[4 1 5 2 6 9 8 7 3]
 [7 6 3 5 8 1 9 2 4]
 [9 2 8 4 7 3 1 6 5]
 [6 7 2 1 3 5 4 8 9]
 [8 3 1 9 4 6 7 5 2]
 [5 4 9 7 2 8 3 1 6]
 [2 8 4 3 5 7 6 9 1]
 [1 5 7 6 9 4 2 3 8]
 [3 9 6 8 1 2 5 4 7]]
